### ISSUE TITLE
No audio since Build Nov 16 2020 on Windows 7

### ISSUE THREAD

**Issue by a7mag3ddon** [loganmc10/m64p#113]
I dont know if reported but the last working version that has audio on windows 7 (for me) is Nov 16 2020

All versions after this have no sound, i tested all in between.

I know im using an old version of windows now but thought id let you know, if your not supporting 7 then fair enough.

thanks.

PS.. tested all between nov and jan 4th versions on W10 and all have sound :-)

**Comment by loganmc10** [comment]
Yeah Windows 7 is not supported

**Comment by a7mag3ddon** [comment]
Would you mind explaining what changed between the Nov 14th version and the ones that started a few weeks later?

**Comment by loganmc10** [comment]
I have no idea, that's why Windows 7 is not supported. I don't have a Win 7 machine to test things on.

m64p depends on other libraries to work (Qt for example). The audio plugin depends on libsamplerate. Since Windows 7 is end of life, any of those dependant plugins could drop support for it at any moment. I don't read through the change logs of every library, so I'm not really sure what could have caused the issue

**Comment by Zytxa** [comment]
I copy this two file from build Oct 8 2020 and get the sound work again at newest build Jul 27 2021
mupen64plus-audio-sdl2.dll
libsamplerate-0.dll

**Comment by Zytxa** [comment]
my PC still run on Windows 7, I copy this two file from build Oct 8 2020 and get the sound work again at newest build Jul 27 2021

mupen64plus-audio-sdl2.dll
libsamplerate-0.dll

**Comment by a7mag3ddon** [comment]
Why was that other guys fix deleted?
