### ISSUE TITLE
Is there a way to play netplay if one person uses Linux and the other one uses Windows?

### ISSUE THREAD

**Issue by Toadfield** [loganmc10/m64p#55]
I tried to play with a friend,I hosted a Server on the stable M64P AUR Package (not the -git version),he tried to join with the stable windows 64 bit version,but he couldn't join,is the problem that we use different os or something other?

**Comment by loganmc10** [comment]
> ,but he couldn't join

It would be helpful to know what the exact error message was, but yes cross platform play is supported. However, only the releases at: https://github.com/loganmc10/m64p/releases are supported, not AUR packages

**Comment by Toadfield** [comment]
there Error message is "error:client doesn't match"

**Comment by loganmc10** [comment]
Yes, so the issue is that the version in the AUR doesn't match the version the Windows user downloaded at https://github.com/loganmc10/m64p/releases

Everyone needs to have the exact same version for netplay to work, or desyncs will occur. This is why I'd suggest everyone get their stuff from https://github.com/loganmc10/m64p/releases

**Comment by Toadfield** [comment]
I tested the version with the link you send,It works,but the problem is with updates,do I get auto updates with this version or do I have to download it manually everytime I want a new version or is it like with package with repositories?

**Comment by loganmc10** [comment]
You'd have to download a new version manually when they come out, GitHub allows you to subscribe to releases so you'd get an email when a new version is released

**Comment by Toadfield** [comment]
now it works,I forgot to close
