### ISSUE TITLE
Sound problem

### ISSUE THREAD

**Issue by XYZ964** [loganmc10/m64p#87]
Hi!
Since october 12th version, there is no sound at all while running the emulator.
I read using Window 7 64 bits could be the problem, but since the emu runs well and that is the only issue i noticed, i do hope you could take a look and fix it. 
Thanks a lot in advance.

**Comment by loganmc10** [comment]
If you're using Windows 7, no there is nothing I can do to help. Part of the problem is that this project relies on many libraries to work (for instance, libsamplerate for audio). There is no telling when one of these libraries will drop support for Windows 7, or any other unsupported OS.

For this reason, unsupported OSes are....unsupported.
